name: Open issues

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  move-assigned-card:
    runs-on: ubuntu-22.04
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Proeco Dev
          column: 🧐 Open
          repo-token: ${{ secrets.ISSUE_OPEN_TOKEN }}
